
### obtener todos los characters
GET http://localhost:3000/api/characters

### obtener un character por id
### id es el id del character, no el _id de mongo. El id es el que se genera al crear el character.
GET http://localhost:3000/api/characters/a02b91bc-3769-4221-beb1-d7a3aeba7dad

### obtener un character por _id 
GET http://localhost:3000/api/characters/6817a406aa10cea390b5f899

### crear un character
POST http://localhost:3000/api/characters
Content-Type: application/json

{
 "name": "Luke Skywalker",
 "characterClass": "Jedi",
 "level": 1,
 "hp": 100,
 "mana": 100,
 "attack": 10,
 "items": ["Lightsaber", "X-Wing"]
}

### modificar un character
### PUT es idempotente, PATCH no lo es. Esto significa que si haces la misma peticion varias veces, el resultado sera el mismo.
### En cambio, PATCH no es idempotente, por lo que si haces la misma peticion varias veces, el resultado sera diferente.
PUT http://localhost:3000/api/characters/a02b91bc-3769-4221-beb1-d7a3aeba7dad
Content-Type: application/json

{
 "name": "Anakin Skywalker",
 "characterClass": "Jedi",
 "level": 50,
 "hp": 300,
 "mana": 500,
 "attack": 100,
 "items": ["Lightsaber", "R2-D2"]
}

### modificar un character (para modificaciones parciales o incrementales)
### PATCH es para modificar solo una parte del recurso, no todo el recurso.
PATCH  http://localhost:3000/api/characters/a02b91bc-3769-4221-beb1-d7a3aeba7dad
Content-Type: application/json

{
 "name": "Anakin Skywalker",
 "characterClass": "Jedi",
 "level": 70,
 "items": ["Lightsaber", "R2-D2", "501st Legion"]
}

### eliminar un character
DELETE http://localhost:3000/api/characters/a02b91bc-3769-4221-beb1-d7a3aeba7dad
